package symbols

// -------
// SYMBOLS
// -------

// General

const (
	Bullet            = "●"
	CheckboxCircleOff = "Ⓘ"
	CheckboxCircleOn  = "ⓧ"
	CheckboxOff       = "☐"
	CheckboxOn        = "☒"
	Cross             = "✖"
	Dot               = "․"
	Ellipsis          = "…"
	Hamburger         = "☰"
	Heart             = "♥"
	Home              = "⌂"
	Info              = "ℹ"
	Lozenge           = "◆"
	LozengeOutline    = "◇"
	Mustache          = "෴"
	Nodejs            = "⬢"
	Play              = "▶"
	Pointer           = "❯"
	PointerSmall      = "›"
	RadioOff          = "◯"
	RadioOn           = "◉"
	Smiley            = "㋡"
	Star              = "★"
	Tick              = "✔"
	Warning           = "⚠"
)

// Math

const (
	Degree                   = "°"
	DegreeCelsius            = "℃"
	DegreeFahrenheit         = "℉"
	And                      = "∧"
	Angle                    = "∠"
	Approx                   = "≈"
	Empty                    = "∅"
	Equals                   = "="
	Exists                   = "∃"
	ForAll                   = "∀"
	Infinity                 = "∞"
	Intersect                = "∩"
	IsIn                     = "∈"
	IsNotIn                  = "∉"
	Minus                    = "−"
	Nabla                    = "∇"
	Not                      = "¬"
	NotEquals                = "≠"
	Or                       = "∨"
	Percent                  = "%"
	Permille                 = "‰"
	Plus                     = "+"
	PlusMinus                = "±"
	Subset                   = "⊂"
	Superset                 = "⊃"
	Union                    = "∪"
	RightAngle               = "∟"
	Therefore                = "∴"
	Because                  = "∵"
	ProportionalTo           = "∝"
	NotProportionalTo        = "∝̸"
	NotInfinity              = "∞̸"
	Parallel                 = "∥"
	NotParallel              = "∦"
	Perpendicular            = "⊥"
	NotPerpendicular         = "⊥̸"
	Identical                = "≡"
	NotIdentical             = "≢"
	NotTilde                 = "≁"
	NotAsymptoticallyEqualTo = "≄"
	AlmostEqual              = "≈"
	NotEqual                 = "≠"
	LessOrEqual              = "≤"
	GreaterOrEqual           = "≥"
	NotAlmostEqualTo         = "≉"
	NotLessThan              = "≮"
	NotLessThanOrEqualTo     = "≰"
	NotGreaterThanOrEqualTo  = "≱"
	NotGreaterThan           = "≯"
	NotSubset                = "⊄"
	NotSuperset              = "⊅"
	NotSubsetNorEqualTo      = "⊈"
	NotSupersetNorEqualTo    = "⊉"
)

// Arrows

const (
	ArrowUp           = "↑"
	ArrowDown         = "↓"
	ArrowLeft         = "←"
	ArrowRight        = "→"
	ArrowLeftRight    = "↔"
	ArrowUpDown       = "↕"
	ArrowUpDownAlt    = "↨"
	ArrowUpLeft       = "↖"
	ArrowUpRight      = "↗"
	ArrowDownLeft     = "↙"
	ArrowDownRight    = "↘"
	ArrowLeftUp       = "↺"
	ArrowLeftDown     = "↻"
	ArrowRightUp      = "↻"
	ArrowRightDown    = "↷"
	ArrowUpLeftAlt    = "⇖"
	ArrowUpRightAlt   = "⇗"
	ArrowDownLeftAlt  = "⇙"
	ArrowDownRightAlt = "⇘"
	ArrowLeftRightAlt = "⇆"
)

// Currency

const (
	CurrencyDollar  = "$"
	CurrencyCent    = "¢"
	CurrencyPound   = "£"
	CurrencyRupee   = "₹"
	CurrencyYen     = "¥"
	CurrencyEuro    = "€"
	CurrencyBitcoin = "₿"
)

// Brackets

const (
	BracketSquareLeft  = "["
	BracketSquareRight = "]"
	BracketCurlyLeft   = "{"
	BracketCurlyRight  = "}"
	BracketAngleLeft   = "⟨"
	BracketAngleRight  = "⟩"
	BracketRoundLeft   = "("
	BracketRoundRight  = ")"
	BracketDoubleLeft  = "«"
	BracketDoubleRight = "»"
)

// Square

const (
	Square            = "█"
	SquareDarkShade   = "▓"
	SquareMediumShade = "▒"
	SquareLightShade  = "░"
	SquareTop         = "▀"
	SquareBottom      = "▄"
	SquareLeft        = "▌"
	SquareRight       = "▐"
	SquareCenter      = "■"
	SquareSmall       = "◻"
	SquareSmallFilled = "◼"
)

// Circle

const (
	Circle       = "●"
	CircleFilled = "◉"
	CircleDotted = "◌"
	CircleDouble = "◎"
	CircleCircle = "ⓞ"
	CircleCross  = "ⓧ"
	CirclePipe   = "Ⓘ"
)

// Triangle

const (
	TriangleUp         = "▲"
	TriangleUpSmall    = "▴"
	TriangleDown       = "▼"
	TriangleDownSmall  = "▾"
	TriangleLeftSmall  = "◂"
	TriangleRightSmall = "▸"
	TriangleUpOutline  = "△"
	TriangleLeft       = "◀"
	TriangleRight      = "▶"
)

// Subscripts

const (
	SubscriptZero  = "₀"
	SubscriptOne   = "₁"
	SubscriptTwo   = "₂"
	SubscriptThree = "₃"
	SubscriptFour  = "₄"
	SubscriptFive  = "₅"
	SubscriptSix   = "₆"
	SubscriptSeven = "₇"
	SubscriptEight = "₈"
	SubscriptNine  = "₉"
)

// Fractions

const (
	FractionOneHalf       = "½"
	FractionOneThird      = "⅓"
	FractionOneQuarter    = "¼"
	FractionOneFifth      = "⅕"
	FractionOneSixth      = "⅙"
	FractionOneEighth     = "⅛"
	FractionTwoThirds     = "⅔"
	FractionTwoFifths     = "⅖"
	FractionThreeQuarters = "¾"
	FractionThreeFifths   = "⅗"
	FractionThreeEighths  = "⅜"
	FractionFourFifths    = "⅘"
	FractionFiveSixths    = "⅚"
	FractionFiveEighths   = "⅝"
	FractionSevenEighths  = "⅞"
	FractionOneSeventh    = "⅐"
	FractionOneNinth      = "⅑"
	FractionOneTenth      = "⅒"
)

// Line

const (
	Line                                        = "─"
	LineBackslash                               = "╲"
	LineBold                                    = "━"
	LineCross                                   = "╳"
	LineDashed0                                 = "┄"
	LineDashed1                                 = "┅"
	LineDashed10                                = "╼"
	LineDashed11                                = "╾"
	LineDashed12                                = "−"
	LineDashed13                                = "–"
	LineDashed14                                = "‐"
	LineDashed15                                = "⁃"
	LineDashed2                                 = "┈"
	LineDashed3                                 = "┉"
	LineDashed4                                 = "╌"
	LineDashed5                                 = "╍"
	LineDashed6                                 = "╴"
	LineDashed7                                 = "╶"
	LineDashed8                                 = "╸"
	LineDashed9                                 = "╺"
	LineDouble                                  = "═"
	LineDownBoldLeft                            = "┒"
	LineDownBoldLeftBold                        = "┓"
	LineDownBoldLeftBoldRight                   = "┱"
	LineDownBoldLeftBoldRightBold               = "┳"
	LineDownBoldLeftRight                       = "┰"
	LineDownBoldLeftRightBold                   = "┲"
	LineDownBoldRight                           = "┎"
	LineDownBoldRightBold                       = "┏"
	LineDownDoubleLeft                          = "╖"
	LineDownDoubleLeftDouble                    = "╗"
	LineDownDoubleLeftDoubleRightDouble         = "╦"
	LineDownDoubleLeftRight                     = "╥"
	LineDownDoubleRight                         = "╓"
	LineDownDoubleRightDouble                   = "╔"
	LineDownLeft                                = "┐"
	LineDownLeftArc                             = "╮"
	LineDownLeftBold                            = "┑"
	LineDownLeftBoldRight                       = "┭"
	LineDownLeftBoldRightBold                   = "┯"
	LineDownLeftDouble                          = "╕"
	LineDownLeftDoubleRightDouble               = "╤"
	LineDownLeftRight                           = "┬"
	LineDownLeftRightBold                       = "┮"
	LineDownRight                               = "┌"
	LineDownRightArc                            = "╭"
	LineDownRightBold                           = "┍"
	LineDownRightDouble                         = "╒"
	LineSlash                                   = "╱"
	LineUpBoldDownBoldLeft                      = "┨"
	LineUpBoldDownBoldLeftBold                  = "┫"
	LineUpBoldDownBoldLeftBoldRight             = "╉"
	LineUpBoldDownBoldLeftBoldRightBold         = "╋"
	LineUpBoldDownBoldLeftRight                 = "╂"
	LineUpBoldDownBoldLeftRightBold             = "╊"
	LineUpBoldDownBoldRight                     = "┠"
	LineUpBoldDownBoldRightBold                 = "┣"
	LineUpBoldDownLeft                          = "┦"
	LineUpBoldDownLeftBold                      = "┩"
	LineUpBoldDownLeftBoldRight                 = "╃"
	LineUpBoldDownLeftBoldRightBold             = "╇"
	LineUpBoldDownLeftRight                     = "╀"
	LineUpBoldDownLeftRightBold                 = "╄"
	LineUpBoldDownRight                         = "┞"
	LineUpBoldDownRightBold                     = "┡"
	LineUpBoldLeft                              = "┚"
	LineUpBoldLeftBold                          = "┛"
	LineUpBoldLeftBoldRight                     = "┹"
	LineUpBoldLeftBoldRightBold                 = "┻"
	LineUpBoldLeftRight                         = "┸"
	LineUpBoldLeftRightBold                     = "┺"
	LineUpBoldRight                             = "┖"
	LineUpBoldRightBold                         = "┗"
	LineUpDoubleDownDoubleLeft                  = "╢"
	LineUpDoubleDownDoubleLeftDouble            = "╣"
	LineUpDoubleDownDoubleLeftDoubleRightDouble = "╬"
	LineUpDoubleDownDoubleLeftRight             = "╫"
	LineUpDoubleDownDoubleRight                 = "╟"
	LineUpDoubleDownDoubleRightDouble           = "╠"
	LineUpDoubleLeft                            = "╜"
	LineUpDoubleLeftDouble                      = "╝"
	LineUpDoubleLeftDoubleRightDouble           = "╩"
	LineUpDoubleLeftRight                       = "╨"
	LineUpDoubleRight                           = "╙"
	LineUpDoubleRightDouble                     = "╚"
	LineUpDownBoldLeft                          = "┧"
	LineUpDownBoldLeftBold                      = "┪"
	LineUpDownBoldLeftBoldRight                 = "╅"
	LineUpDownBoldLeftBoldRightBold             = "╈"
	LineUpDownBoldLeftRight                     = "╁"
	LineUpDownBoldLeftRightBold                 = "╆"
	LineUpDownBoldRight                         = "┟"
	LineUpDownBoldRightBold                     = "┢"
	LineUpDownLeft                              = "┤"
	LineUpDownLeftBold                          = "┥"
	LineUpDownLeftBoldRight                     = "┽"
	LineUpDownLeftBoldRightBold                 = "┿"
	LineUpDownLeftDouble                        = "╡"
	LineUpDownLeftDoubleRightDouble             = "╪"
	LineUpDownLeftRight                         = "┼"
	LineUpDownLeftRightBold                     = "┾"
	LineUpDownRight                             = "├"
	LineUpDownRightBold                         = "┝"
	LineUpDownRightDouble                       = "╞"
	LineUpLeft                                  = "┘"
	LineUpLeftArc                               = "╯"
	LineUpLeftBold                              = "┙"
	LineUpLeftBoldRight                         = "┵"
	LineUpLeftBoldRightBold                     = "┷"
	LineUpLeftDouble                            = "╛"
	LineUpLeftDoubleRightDouble                 = "╧"
	LineUpLeftRight                             = "┴"
	LineUpLeftRightBold                         = "┶"
	LineUpRight                                 = "└"
	LineUpRightArc                              = "╰"
	LineUpRightBold                             = "┕"
	LineUpRightDouble                           = "╘"
	LineVertical                                = "│"
	LineVerticalBold                            = "┃"
	LineVerticalDashed0                         = "┆"
	LineVerticalDashed1                         = "┇"
	LineVerticalDashed10                        = "╽"
	LineVerticalDashed11                        = "╿"
	LineVerticalDashed2                         = "┊"
	LineVerticalDashed3                         = "┋"
	LineVerticalDashed4                         = "╎"
	LineVerticalDashed5                         = "╏"
	LineVerticalDashed6                         = "╵"
	LineVerticalDashed7                         = "╷"
	LineVerticalDashed8                         = "╹"
	LineVerticalDashed9                         = "╻"
	LineVerticalDouble                          = "║"
)

// Music

const (
	MusicNote       = "♪"
	MusicNoteBeamed = "♫"
)
